version: '3'

services:
  api:
    image: cezeitar/devan_api:v1
    container_name: devan-api
    volumes:
      - ./models:/app/models
    environment:
      - DEVAN_API_HOSTNAME=0.0.0.0
      - DEVAN_API_PORT=8080
      - DEVAN_MODEL_V1_FILENAME=/app/models/Devanagari_model.joblib

  server:
    depends_on:
      - api
    image: nginx:latest
    container_name: devan-rev-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'